### ISSUE TITLE
contacts

### ISSUE THREAD

**Issue by bruel-gabrielsson** [ediziks/discord-GPT3-davinci-bot#1]
Hi! Would love to talk to you about a project. Could I get your contacts or could you email me at rgabriel@stanford.edu? Thanks!

**Comment by ediziks** [comment]
@bruel-gabrielsson feel free to write down in here if I can help out. Closing the issue due to not being a related issue.

**Comment by bruel-gabrielsson** [comment]
Hey!

My name is Rickard Brüel Gabrielsson (http://bruel.org/) and I’m a Stanford
graduate and PhD at MIT as well as a researcher at Unbox AI
(www.unboxai.com) together with
Stanford Professor Gunnar Carlsson (
https://en.wikipedia.org/wiki/Gunnar_Carlsson) and other passionate
researchers. We use language modeling techniques to understand consumption,
i.e. pooling all data and training a single model on all data in an
unsupervised/self-supervised fashion, seeing all functions as downstream
fine-tuning tasks (the results are astounding). We really like
your work and would love to schedule a meeting to discuss possibilities of
you joining our team.


Here’s a short video about what we do:
https://www.loom.com/share/18f9d556859c46a79e5b3c4eb2460ee0


All the best,



Rickard Brüel Gabrielsson


LinkedIn
<https://www.linkedin.com/in/rickard-br%C3%BCel-gabrielsson-0a61375a>
Tel: 650 353 8738 | Email: ***@***.***

This electronic mail transmission may contain private, privileged
or proprietary information intended only for the person(s) named. If
you received this transmission in error, please notify the sender by
reply e-mail and then delete the message.
